### ISSUE TITLE
It may cause debug break due to a null reference exception in ReApplyOptionalRouteParameterOperationFilter.cs

### ISSUE THREAD

**Issue by NightGreyMoon** [fooberichu150/swagger-optional-route-parameters#1]
Need to update it to 
var httpMethodWithOptional = httpMethodAttributes?.FirstOrDefault(m => m.Template != null && m.Template.Contains("?"));

**Comment by fooberichu150** [comment]
Never ran into that, good catch.  Updated and committed.
